name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    strategy:
      matrix:
        # until github actions has native arm64 runners, use QEMU and multi-platform build
        arch: [ {syntax0: amd64, syntax1: x86_64, platform: 'linux/amd64' }, {syntax0: arm64, syntax1: aarch64, platform: 'linux/arm64' } ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.arch.syntax0 }}-${{ github.sha }},${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ matrix.arch.syntax0 }}-${{ github.ref_name }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.arch.platform }}
          build-args: |
            ARCH=${{ matrix.arch.syntax0 }}
            ARCH2=${{ matrix.arch.syntax1 }}
